# Generated by Django 6.0.5 on 2026-06-06 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Назва філії')),
                ('address', models.CharField(max_length=300, verbose_name='Адреса')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='Телефон')),
                ('work_hours', models.CharField(default='10:00 - 22:00', max_length=100, verbose_name='Години роботи')),
                ('special', models.TextField(blank=True, verbose_name='Особливості/Спецпропозиції')),
            ],
            options={
                'verbose_name': 'Філія',
                'verbose_name_plural': 'Філії',
                'ordering': ['name'],
            },
        ),
    ]
