# Generated by Django 6.0.5 on 2026-06-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_branch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
